K8s
PokeAPI/pokeapi pull request #623
Opened 2021-05-31 20:57 UTC by Naramsim

Hello everyone,

I had to pick up k8s again for a certification and thought about creating a deployment for PokeAPI. I don't know if anyone that contributes to this repository is familiar with k8s, but anyway, feel free to ask as many questions as you want.

I used Kustomize to allow anyone to deploy a cluster with their own secrets/config in the simplest way. Basically one needs to configure `kubectl` to point to a cluster and then they have to run `kubectl -k apply` and voila' a copy of pokeapi will be deployed on the cluster. In the `README.md` I wrote I small guide about how to set everything up, you can read that to see how to build the data etc.

The k8s files are tested as well with a Github action.

2021-06-01 01:22 UTC, phalt requested changes

2021-06-01 01:22 UTC, phalt commented on .dockerignore
> -graphql
I remember you added this in another PR, might need to rebase vs master.

2021-06-01 01:22 UTC, phalt commented on .github/workflows/kustomize.yml
> +          test "$last_command" -eq 1
newline at end of file?

2021-06-01 13:27 UTC, Naramsim commented
I've added a yamllint job to check the syntax

2021-06-23 08:27 UTC, Naramsim commented
Forcing merge

2021-06-23 08:27 UTC, merged

2021-06-23 08:30 UTC, pokeapi-machine-user commented
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).