Added Scarlet / Violet data for Pokemon Names / Pokemon Forms / Pokemon
PokeAPI/pokeapi pull request #793
Opened 2022-12-09 18:38 UTC by giginet

I added some info proceeded by #778 

I updated followings:

- pokemon
- pokemon_names (Japanese/English)
- pokemon_forms

Some column is missing

- pokemon.base_experience
- pokemon_names.genus
- pokemon_forms/pokemon.order

2022-12-09 20:03 UTC, maiko-ando commented on data/v2/csv/pokemon_species_names.csv
> +933,1,ナミイカル,
@giginet 
ポケモン名Typoしてますね

2022-12-09 20:04 UTC, maiko-ando commented on data/v2/csv/pokemon_species_names.csv
> +965,1,キヨジオーン,
@giginet 
キョジオーン

2022-12-09 20:05 UTC, maiko-ando commented on data/v2/csv/pokemon_species_names.csv
> +986,1,テツノウダチ,
@giginet 
テツノワダチ

2022-12-09 21:57 UTC, giginet commented
gender_rate was wrong. I‘ll fix this tomorrow

2022-12-10 15:19 UTC, Naramsim commented
Hi @giginet , thanks for the new data!

Could you also take a look at this: https://github.com/PokeAPI/pokeapi/pull/783#issuecomment-1337853382 ?

2022-12-11 06:43 UTC, giginet commented
I miss understood, `gender_rate` is not included in this diff. So this looks good.
Could you review it? @Naramsim

2022-12-11 09:11 UTC, Naramsim requested changes

2022-12-11 09:11 UTC, Naramsim commented on data/v2/csv/pokemon.csv
> +906,sprigatito,906,0.4,4.1,,906,1
Hi, `height` and `weight` use decimetres and hectograms. Moreover I don't think we support _floats`. So you just need to multiply the values by 10.

2022-12-11 14:56 UTC, giginet commented on data/v2/csv/pokemon.csv
> +906,sprigatito,906,0.4,4.1,,906,1
Fixed
https://github.com/PokeAPI/pokeapi/pull/793/commits/b3eebc600747cb2261d0884924dbe392b00a8bc2

2023-01-02 20:38 UTC, oneirocosm commented
I've noticed that the current order of the Paldean species follows the initial data-mined order from Scarlet and Violet.  What is the plan for when the official order is eventually released (will probably happen when Pokemon Home updates)?  I suppose you could either:

1. Keep the current order and update the National Dex Numbers in pokemon_dex_numbers.csv
2. Update the current order to match the official national dex order

If you do go with 2, it may be possible to do some of that work now using [the other popular order](https://bulbapedia.bulbagarden.net/wiki/User:ScraftyIsTheBest/Tentative_Generation_IX_National_Pok%C3%A9dex_Numbers) that I've been seeing lately.  There is no guarantee that it will match, but I think it is much more likely to than the current ordering based off what I'm reading [here](https://www.smogon.com/forums/threads/scarlet-violet-leaks-thread-data-mechanics.3709515/page-377#post-9420325]) and [here](https://www.smogon.com/forums/members/slp32.579658/#profile-post-2452287).

2023-01-03 07:11 UTC, giginet commented
@oneirocosm Make sense. 
I also worry about current internal data including missing numbers.
I guess this internal numbering might be changed in a future series.
It's important to decide how to number IDs in PokéAPI.

Could somebody be concerned about which way is better?

In the latter way, other following data must be migrated to new IDs.

2023-01-08 16:17 UTC, merged

2023-01-08 16:20 UTC, pokeapi-machine-user commented
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

2023-01-08 18:47 UTC, giginet commented
@Naramsim How about these discussions? https://github.com/PokeAPI/pokeapi/pull/793#issuecomment-1369192812

Should we use current numbering?

2023-01-08 21:25 UTC, Naramsim commented
no clue, I didn't have time to read it. Could you and @oneirocosm decide?

2023-01-09 05:51 UTC, giginet commented
@Naramsim Those discussions are important for future compatibilities.
So they should be decided by a core maintainer. We are not maintainers.

If you don't have any concerns, I'll process the following PRs. However, I think it's tough to modify this data structure in the future.

2023-01-09 12:08 UTC, Naramsim commented
What about setting the `order` as a `null`able field and leaving it empty? Until the official numbering is released?

2023-01-10 07:58 UTC, giginet commented
Sounds good. I'll use the current numbering for the following PRs.

2023-01-12 17:25 UTC, lordkyuusei commented
A promotional video came out a few hours ago with what seems like an official ID numbering for each Paldean Pokemon, if it helps: https://www.youtube.com/watch?v=pa08Y-fhfTI (starting at 6:36)

2023-01-13 10:30 UTC, Naramsim commented
yes, other people in another issue are aware of that