Fix pound move
PokeAPI/pokeapi pull request #885
Opened 2023-05-30 14:43 UTC by Naramsim

2023-05-30 18:24 UTC, Sunlis requested changes

2023-05-30 18:24 UTC, Sunlis commented on data/v2/csv/pokemon_moves.csv
Move `876` is still listed in this file 45 times. There should only be one occurence - for pokemon `1009`. Move `875` is correctly only present in this file once.

2023-05-30 21:06 UTC, JulesLetters commented on data/v2/csv/pokemon_moves.csv
I've created a patch to address this but don't have permissions for the branch.

2023-05-31 08:41 UTC, Naramsim commented on data/v2/csv/pokemon_moves.csv
You can create a PR from your forked repo

2023-05-31 14:51 UTC, JulesLetters commented on data/v2/csv/pokemon_moves.csv
Alright, that's in. https://github.com/PokeAPI/pokeapi/pull/886
It's a merge of my own 'pound' branch to the existing one. Let me know if you'd rather have one merging that 'pound' branch to 'master'.

2023-06-02 16:50 UTC, Sunlis approved these changes

2023-06-03 19:08 UTC, merged

2023-06-03 19:14 UTC, pokeapi-machine-user commented
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

2023-06-03 19:45 UTC, pokeapi-machine-user commented
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).

2023-06-03 20:27 UTC, pokeapi-machine-user commented
A [PokeAPI/api-data](https://github.com/PokeAPI/api-data) refresh has started. In 45 minutes the staging branch of [PokeAPI/api-data](https://github.com/PokeAPI/api-data/tree/staging) will be pushed with the new generated data. <br><br> The staging branch will be deployed in our [staging environment](https://staging.pokeapi.co/api/v2/) and you will be able to review the entire API. <br><br> A Pull Request ([master](https://github.com/PokeAPI/api-data/tree/master)<-[staging](https://github.com/PokeAPI/api-data/tree/staging)) will be also created at [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) and assigned to the PokeAPI Core team to be reviewed. If approved and merged new data will soon be available worldwide at [pokeapi.co](https://pokeapi.co/api/v2/).

2023-06-03 20:56 UTC, pokeapi-machine-user commented
The updater script has finished its job and has now opened a Pull Request towards [PokeAPI/api-data](https://github.com/PokeAPI/api-data/pulls) with the updated data. <br><br> You can see the Pull Request deployed at our [staging environment](https://staging.pokeapi.co/api/v2/) when [CircleCI deploy](https://app.circleci.com/pipelines/github/PokeAPI/deploy) will be finished (_check the started time of the last build_).